[package]
name = "shared-security"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["tracing"] }
tower-http = { version = "0.5", features = ["cors"] }
tracing = "0.1"
shared-config = { path = "../config" }
shared-errors = { path = "../errors" }
