global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape metrics from PesaBit services
  - job_name: 'pesabit-api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'pesabit-user-service'
    static_configs:
      - targets: ['user-service:8001']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'pesabit-payment-service'
    static_configs:
      - targets: ['payment-service:8002']
    metrics_path: /metrics
    scrape_interval: 10s

  # Infrastructure monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for host metrics (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']