server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/pesabit-(.*)'
        target_label: service
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_name']
        regex: '/pesabit-.*'
        target_label: __logs_path__
        replacement: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log